obj-y := dev2devfs_glue.o dev2devfs_glue_helper.o fcntl_glue.o kmalloc_glue.o \
	pmm_glue.o resource_glue.o schedule_glue.o timer_glue.o uaccess_glue.o ucore_stat2linux_stat.o irq_glue.o kthread_glue.o idr_glue.o

obj-$(UCONFIG_ARM_BOARD_GOLDFISH) += arm_iomap_glue.o
obj-$(UCONFIG_ARM_BOARD_PANDABOARD) += arm_iomap_glue.o
